# Generated by Django 4.1.2 on 2022-11-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_rename_numbercontract_visit_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de visita'),
        ),
    ]
