# Generated by Django 4.1.2 on 2022-10-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField(verbose_name='Rut')),
                ('dv', models.CharField(max_length=1, verbose_name='Dígito verificador')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('comune', models.CharField(max_length=50, verbose_name='Comuna')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('type', models.CharField(max_length=10, verbose_name='Tipo de usuario')),
                ('id_client', models.PositiveIntegerField(verbose_name='Identificador Cliente')),
                ('username', models.CharField(max_length=10, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=10, verbose_name='Clave de usuario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-created'],
            },
        ),
    ]
