# Generated by Django 4.1.2 on 2022-10-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='numbercontract',
            new_name='contract',
        ),
    ]
