# Generated by Django 4.1.2 on 2022-11-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_numbercontract_contract_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dateend',
            field=models.DateField(verbose_name='Fecha de finalizacion'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='datestart',
            field=models.DateField(verbose_name='Fecha de comienzo'),
        ),
    ]
