# Generated by Django 4.1.3 on 2022-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_dateend_alter_contract_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='mensualprice',
            field=models.PositiveIntegerField(null=True, verbose_name='Monto mensual'),
        ),
    ]
