# Generated by Django 4.1.3 on 2022-12-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_mensualprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha a pagar')),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('payment', models.PositiveIntegerField(null=True, verbose_name='Monto pagado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
            options={
                'verbose_name': 'detallo de pago contrato',
                'verbose_name_plural': 'detalle de pagos contrato',
                'ordering': ['-created'],
            },
        ),
    ]
