# Generated by Django 4.1.2 on 2022-10-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportaccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripcion del accidente')),
                ('zone', models.CharField(max_length=100, verbose_name='Area del accidente')),
                ('date', models.DateField(null=True, verbose_name='Fecha del accidente')),
                ('hour', models.TimeField(null=True, verbose_name='Hora del accidente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'ReportarAccidente',
                'verbose_name_plural': 'ReportarAccidentes',
                'ordering': ['-created'],
            },
        ),
    ]
