# Generated by Django 4.1.2 on 2022-10-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
