# Generated by Django 4.1.2 on 2022-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0002_alter_commune_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='commune',
            field=models.CharField(max_length=100, verbose_name='Comuna'),
        ),
    ]
