# Generated by Django 4.1.2 on 2022-10-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.CharField(max_length=200, verbose_name='Asistentes')),
                ('profecional', models.CharField(max_length=20, verbose_name='Profesional')),
                ('topic', models.CharField(max_length=500, verbose_name='Tema de capacitacion')),
                ('date', models.CharField(max_length=100, verbose_name='Fecha de capacitacion')),
                ('id_client', models.CharField(max_length=50, verbose_name='Identificador cliente')),
                ('id_contract', models.CharField(max_length=50, verbose_name='Identificador contrato')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'capacitacion',
                'verbose_name_plural': 'capacitaciones',
                'ordering': ['-created'],
            },
        ),
    ]
