# Generated by Django 4.1.2 on 2022-10-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitations', '0002_rename_user_capacitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitation',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
