# Generated by Django 4.1.2 on 2022-10-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
        ('contracts', '0002_rename_numbercontract_contract_contract'),
        ('clients', '0003_alter_client_updated'),
        ('capacitations', '0004_remove_capacitation_profecional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitation',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='capacitation',
            name='id_contract',
        ),
        migrations.AddField(
            model_name='capacitation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='capacitation',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='capacitation',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professional'),
        ),
    ]
