# Generated by Django 4.1.2 on 2022-11-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitations', '0005_remove_capacitation_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitation',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de capacitacion'),
        ),
    ]
