# Generated by Django 4.1.2 on 2022-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitations', '0006_alter_capacitation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitation',
            name='state',
            field=models.CharField(max_length=10, null=True, verbose_name='Estado de la asesoría'),
        ),
    ]
