# Generated by Django 4.1.2 on 2022-11-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialadvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=200, verbose_name='Motivo de solicitud')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion de lo sucedido')),
                ('date', models.DateField(null=True, verbose_name='Fecha de asesoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'asesoriaespecial',
                'verbose_name_plural': 'asesoriasespeciales',
                'ordering': ['-created'],
            },
        ),
    ]
