# Generated by Django 4.1.2 on 2022-11-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_userclient'),
        ('specialadvisorys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialadvisory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userclient'),
        ),
    ]
