# Generated by Django 4.1.2 on 2022-10-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('clients', '0003_alter_client_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.CharField(max_length=200, verbose_name='Asistentes')),
                ('topic', models.CharField(max_length=500, verbose_name='Tema de asesoria')),
                ('date', models.CharField(max_length=100, verbose_name='Fecha de asesoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professional')),
            ],
            options={
                'verbose_name': 'capacitacion',
                'verbose_name_plural': 'capacitaciones',
                'ordering': ['-created'],
            },
        ),
    ]
