# Generated by Django 4.1.2 on 2022-11-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorys', '0002_advisory_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha de asesoria'),
        ),
    ]
