# Generated by Django 4.1.2 on 2022-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorys', '0003_alter_advisory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='state',
            field=models.CharField(max_length=10, null=True, verbose_name='Estado de la asesoría'),
        ),
    ]
