# Generated by Django 4.1.2 on 2022-11-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_updated'),
        ('contracts', '0003_alter_contract_dateend_alter_contract_datestart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion del checklist')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
            options={
                'verbose_name': 'checklist',
                'verbose_name_plural': 'checklists',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Checklistdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion del detalle')),
                ('result', models.CharField(max_length=500, verbose_name='Resultado del detalle')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist')),
            ],
            options={
                'verbose_name': 'checklist detail',
                'verbose_name_plural': 'checklists detail',
                'ordering': ['-created'],
            },
        ),
    ]
