# Generated by Django 4.1.2 on 2022-10-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_updated'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=500, verbose_name='Caso ')),
                ('action', models.CharField(max_length=1000, verbose_name='Accion tomada para la mejora')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professional')),
            ],
            options={
                'verbose_name': 'Mejora',
                'verbose_name_plural': 'Mejoras',
                'ordering': ['-created'],
            },
        ),
    ]
